language: php

addons:
  postgresql: "9.5"

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - MUSTACHE_IGNORE_NAMES=broken.mustache
    - DB=pgsql
    - MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - make init
  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci behat --profile chrome -vvv
  - moodle-plugin-ci behat --profile default -vvv

jobs:
  include:
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE
